# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_menu = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_menu.sizePolicy().hasHeightForWidth())
        self.Btn_menu.setSizePolicy(sizePolicy)
        self.Btn_menu.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.Btn_menu.setObjectName("Btn_menu")
        self.verticalLayout_2.addWidget(self.Btn_menu)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label_title = QtWidgets.QLabel(self.frame_top)
        self.label_title.setGeometry(QtCore.QRect(350, 10, 401, 17))
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setEnabled(True)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1_dashboard = QtWidgets.QWidget()
        self.page_1_dashboard.setObjectName("page_1_dashboard")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1_dashboard)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.page_1_dashboard)
        self.frame.setStyleSheet("background-color: rgb(77, 77, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.imageCTT = QtWidgets.QLabel(self.frame)
        self.imageCTT.setGeometry(QtCore.QRect(480, 120, 101, 401))
        self.imageCTT.setAutoFillBackground(False)
        self.imageCTT.setStyleSheet("image: url(:/newPrefix/truck.png);\n"
"background-color: none;")
        self.imageCTT.setText("")
        self.imageCTT.setScaledContents(True)
        self.imageCTT.setWordWrap(False)
        self.imageCTT.setObjectName("imageCTT")
        self.sensorCamera = QtWidgets.QFrame(self.frame)
        self.sensorCamera.setGeometry(QtCore.QRect(514, 153, 31, 41))
        self.sensorCamera.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorCamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorCamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorCamera.setObjectName("sensorCamera")
        self.sensorLidar = QtWidgets.QFrame(self.frame)
        self.sensorLidar.setGeometry(QtCore.QRect(440, 80, 171, 81))
        self.sensorLidar.setStyleSheet("background-color: none;")
        self.sensorLidar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensorLidar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorLidar.setObjectName("sensorLidar")
        self.sensorLidar_detect_3 = QtWidgets.QFrame(self.sensorLidar)
        self.sensorLidar_detect_3.setGeometry(QtCore.QRect(10, 7, 153, 153))
        self.sensorLidar_detect_3.setStyleSheet("border-radius: 75px;\n"
"background-color: rgb(255, 255, 255);")
        self.sensorLidar_detect_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorLidar_detect_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorLidar_detect_3.setObjectName("sensorLidar_detect_3")
        self.sensorLidar_main_detect = QtWidgets.QFrame(self.sensorLidar_detect_3)
        self.sensorLidar_main_detect.setGeometry(QtCore.QRect(1, 1, 151, 151))
        self.sensorLidar_main_detect.setStyleSheet("border-radius: 75px;\n"
"background-color: rgb(198, 59, 52);")
        self.sensorLidar_main_detect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorLidar_main_detect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorLidar_main_detect.setObjectName("sensorLidar_main_detect")
        self.sensorLidar_background_2 = QtWidgets.QFrame(self.sensorLidar_main_detect)
        self.sensorLidar_background_2.setGeometry(QtCore.QRect(10, 20, 131, 131))
        self.sensorLidar_background_2.setStyleSheet("border-radius: 65px;\n"
"background-color: rgb(77, 77, 127);")
        self.sensorLidar_background_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensorLidar_background_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorLidar_background_2.setObjectName("sensorLidar_background_2")
        self.sensorLidar_background2_2 = QtWidgets.QFrame(self.sensorLidar_main_detect)
        self.sensorLidar_background2_2.setGeometry(QtCore.QRect(0, 70, 151, 86))
        self.sensorLidar_background2_2.setStyleSheet("background-color: rgba(77, 77, 127)")
        self.sensorLidar_background2_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensorLidar_background2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorLidar_background2_2.setObjectName("sensorLidar_background2_2")
        self.switch_move = QtWidgets.QFrame(self.frame)
        self.switch_move.setGeometry(QtCore.QRect(435, 570, 191, 61))
        self.switch_move.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.switch_move.setFrameShadow(QtWidgets.QFrame.Raised)
        self.switch_move.setObjectName("switch_move")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.switch_move)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.switch_netral_2 = QtWidgets.QLabel(self.switch_move)
        self.switch_netral_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Telugu UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.switch_netral_2.setFont(font)
        self.switch_netral_2.setStyleSheet("color: rgb(85, 255, 127);")
        self.switch_netral_2.setFrameShape(QtWidgets.QFrame.Box)
        self.switch_netral_2.setAlignment(QtCore.Qt.AlignCenter)
        self.switch_netral_2.setObjectName("switch_netral_2")
        self.horizontalLayout_4.addWidget(self.switch_netral_2)
        self.switch_otonom = QtWidgets.QFrame(self.frame)
        self.switch_otonom.setGeometry(QtCore.QRect(430, 30, 191, 41))
        self.switch_otonom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.switch_otonom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.switch_otonom.setObjectName("switch_otonom")
        self.label_switch_otonom = QtWidgets.QLabel(self.switch_otonom)
        self.label_switch_otonom.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_switch_otonom.setFont(font)
        self.label_switch_otonom.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_switch_otonom.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch_otonom.setObjectName("label_switch_otonom")
        self.mathplotlib = QtWidgets.QFrame(self.frame)
        self.mathplotlib.setGeometry(QtCore.QRect(30, 50, 311, 551))
        self.mathplotlib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mathplotlib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mathplotlib.setObjectName("mathplotlib")
        self.sensorUltra = QtWidgets.QFrame(self.frame)
        self.sensorUltra.setGeometry(QtCore.QRect(410, 230, 241, 331))
        self.sensorUltra.setStyleSheet("background-color: none;")
        self.sensorUltra.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensorUltra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra.setObjectName("sensorUltra")
        self.sensorUltra_8 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_8.setGeometry(QtCore.QRect(190, 0, 51, 31))
        self.sensorUltra_8.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_8.setObjectName("sensorUltra_8")
        self.sensorUltra_7 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_7.setGeometry(QtCore.QRect(190, 100, 51, 31))
        self.sensorUltra_7.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_7.setObjectName("sensorUltra_7")
        self.sensorUltra_6 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_6.setGeometry(QtCore.QRect(190, 180, 51, 31))
        self.sensorUltra_6.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_6.setObjectName("sensorUltra_6")
        self.sensorUltra_1 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_1.setGeometry(QtCore.QRect(0, 0, 51, 31))
        self.sensorUltra_1.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_1.setObjectName("sensorUltra_1")
        self.sensorUltra_2 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_2.setGeometry(QtCore.QRect(0, 100, 51, 31))
        self.sensorUltra_2.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_2.setObjectName("sensorUltra_2")
        self.sensorUltra_3 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_3.setGeometry(QtCore.QRect(0, 180, 51, 31))
        self.sensorUltra_3.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_3.setObjectName("sensorUltra_3")
        self.sensorUltra_4 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_4.setGeometry(QtCore.QRect(50, 300, 51, 31))
        self.sensorUltra_4.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_4.setObjectName("sensorUltra_4")
        self.sensorUltra_5 = QtWidgets.QFrame(self.sensorUltra)
        self.sensorUltra_5.setGeometry(QtCore.QRect(140, 300, 51, 31))
        self.sensorUltra_5.setStyleSheet("background-color: rgb(58, 58, 102);")
        self.sensorUltra_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorUltra_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorUltra_5.setObjectName("sensorUltra_5")
        self.circular_feedBrake = QtWidgets.QFrame(self.frame)
        self.circular_feedBrake.setGeometry(QtCore.QRect(680, 230, 181, 181))
        self.circular_feedBrake.setStyleSheet("background-color: none;")
        self.circular_feedBrake.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circular_feedBrake.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circular_feedBrake.setObjectName("circular_feedBrake")
        self.circularBg_feedBrake = QtWidgets.QFrame(self.circular_feedBrake)
        self.circularBg_feedBrake.setGeometry(QtCore.QRect(10, 10, 161, 161))
        self.circularBg_feedBrake.setStyleSheet("QFrame{\n"
"    border-radius: 80px;    \n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circularBg_feedBrake.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularBg_feedBrake.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg_feedBrake.setObjectName("circularBg_feedBrake")
        self.animasi_feedBrake = QtWidgets.QFrame(self.circularBg_feedBrake)
        self.animasi_feedBrake.setGeometry(QtCore.QRect(0, 0, 161, 161))
        self.animasi_feedBrake.setStyleSheet("QFrame{\n"
"    border-radius: 80px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.750 rgb(0, 255, 7), stop:0.745 rgba(255, 255, 255, 0));\n"
"}")
        self.animasi_feedBrake.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animasi_feedBrake.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animasi_feedBrake.setObjectName("animasi_feedBrake")
        self.circularContainer_feedBrake = QtWidgets.QFrame(self.circular_feedBrake)
        self.circularContainer_feedBrake.setGeometry(QtCore.QRect(25, 25, 131, 131))
        self.circularContainer_feedBrake.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer_feedBrake.setStyleSheet("QFrame{\n"
"    border-radius: 65px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer_feedBrake.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer_feedBrake.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer_feedBrake.setObjectName("circularContainer_feedBrake")
        self.layoutWidget_4 = QtWidgets.QWidget(self.circularContainer_feedBrake)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 111, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.infoLayout_feedBrake = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.infoLayout_feedBrake.setContentsMargins(0, 0, 0, 0)
        self.infoLayout_feedBrake.setObjectName("infoLayout_feedBrake")
        self.label_feedBrake_2 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_feedBrake_2.setFont(font)
        self.label_feedBrake_2.setStyleSheet("color: #FFFFFF; background-color: none;")
        self.label_feedBrake_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedBrake_2.setObjectName("label_feedBrake_2")
        self.infoLayout_feedBrake.addWidget(self.label_feedBrake_2, 0, 0, 1, 1)
        self.label_progress_feedBrake = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.label_progress_feedBrake.setFont(font)
        self.label_progress_feedBrake.setStyleSheet("color: rgb(0, 255, 7);; padding: 0px; background-color: none;\n"
"")
        self.label_progress_feedBrake.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progress_feedBrake.setIndent(-1)
        self.label_progress_feedBrake.setObjectName("label_progress_feedBrake")
        self.infoLayout_feedBrake.addWidget(self.label_progress_feedBrake, 1, 0, 1, 1)
        self.label_feedBrake = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_feedBrake.setFont(font)
        self.label_feedBrake.setStyleSheet("color: rgb(148, 148, 216); background-color: none;")
        self.label_feedBrake.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedBrake.setObjectName("label_feedBrake")
        self.infoLayout_feedBrake.addWidget(self.label_feedBrake, 2, 0, 1, 1)
        self.circular_feedspeed = QtWidgets.QFrame(self.frame)
        self.circular_feedspeed.setGeometry(QtCore.QRect(680, 40, 181, 181))
        self.circular_feedspeed.setStyleSheet("background-color: none;")
        self.circular_feedspeed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circular_feedspeed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circular_feedspeed.setObjectName("circular_feedspeed")
        self.circularBg_feedspeed = QtWidgets.QFrame(self.circular_feedspeed)
        self.circularBg_feedspeed.setGeometry(QtCore.QRect(10, 10, 161, 161))
        self.circularBg_feedspeed.setStyleSheet("QFrame{\n"
"    border-radius: 80px;    \n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circularBg_feedspeed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularBg_feedspeed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg_feedspeed.setObjectName("circularBg_feedspeed")
        self.animasi_feedspeed = QtWidgets.QFrame(self.circularBg_feedspeed)
        self.animasi_feedspeed.setGeometry(QtCore.QRect(0, 0, 161, 161))
        self.animasi_feedspeed.setStyleSheet("QFrame{\n"
"    border-radius: 80px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.750 rgba(255, 0, 127, 255), stop:0.745 rgba(255, 255, 255, 0));\n"
"}")
        self.animasi_feedspeed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animasi_feedspeed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animasi_feedspeed.setObjectName("animasi_feedspeed")
        self.circularContainer_feedspeed = QtWidgets.QFrame(self.circular_feedspeed)
        self.circularContainer_feedspeed.setGeometry(QtCore.QRect(25, 25, 131, 131))
        self.circularContainer_feedspeed.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer_feedspeed.setStyleSheet("QFrame{\n"
"    border-radius: 65px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer_feedspeed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer_feedspeed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer_feedspeed.setObjectName("circularContainer_feedspeed")
        self.layoutWidget_3 = QtWidgets.QWidget(self.circularContainer_feedspeed)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 111, 102))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.infoLayout_feedspeed = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.infoLayout_feedspeed.setContentsMargins(0, 0, 0, 0)
        self.infoLayout_feedspeed.setObjectName("infoLayout_feedspeed")
        self.label_feedspeed_2 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_feedspeed_2.setFont(font)
        self.label_feedspeed_2.setStyleSheet("color: #FFFFFF; background-color: none;")
        self.label_feedspeed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedspeed_2.setObjectName("label_feedspeed_2")
        self.infoLayout_feedspeed.addWidget(self.label_feedspeed_2, 0, 0, 1, 1)
        self.label_progress_feedspeed = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.label_progress_feedspeed.setFont(font)
        self.label_progress_feedspeed.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.label_progress_feedspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progress_feedspeed.setIndent(-1)
        self.label_progress_feedspeed.setObjectName("label_progress_feedspeed")
        self.infoLayout_feedspeed.addWidget(self.label_progress_feedspeed, 1, 0, 1, 1)
        self.label_feedspeed = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_feedspeed.setFont(font)
        self.label_feedspeed.setStyleSheet("color: rgb(148, 148, 216); background-color: none;")
        self.label_feedspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedspeed.setObjectName("label_feedspeed")
        self.infoLayout_feedspeed.addWidget(self.label_feedspeed, 2, 0, 1, 1)
        self.circular_feedsteer = QtWidgets.QFrame(self.frame)
        self.circular_feedsteer.setGeometry(QtCore.QRect(680, 420, 181, 181))
        self.circular_feedsteer.setMaximumSize(QtCore.QSize(10000, 10000))
        self.circular_feedsteer.setStyleSheet("background-color: none;")
        self.circular_feedsteer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circular_feedsteer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circular_feedsteer.setObjectName("circular_feedsteer")
        self.circularBg_feedsteer = QtWidgets.QFrame(self.circular_feedsteer)
        self.circularBg_feedsteer.setGeometry(QtCore.QRect(10, 10, 161, 161))
        self.circularBg_feedsteer.setStyleSheet("QFrame{\n"
"    border-radius: 80px;    \n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circularBg_feedsteer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularBg_feedsteer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg_feedsteer.setObjectName("circularBg_feedsteer")
        self.animasi_feedsteer = QtWidgets.QFrame(self.circularBg_feedsteer)
        self.animasi_feedsteer.setGeometry(QtCore.QRect(0, 0, 161, 161))
        self.animasi_feedsteer.setStyleSheet("QFrame{\n"
"    border-radius: 80px;\n"
"    border-strokes:inside;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(85, 170, 255, 255), stop:0.395 rgba(255, 255, 255, 0));\n"
"}")
        self.animasi_feedsteer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animasi_feedsteer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animasi_feedsteer.setObjectName("animasi_feedsteer")
        self.circularContainer_feedsteer = QtWidgets.QFrame(self.circular_feedsteer)
        self.circularContainer_feedsteer.setGeometry(QtCore.QRect(25, 25, 131, 131))
        self.circularContainer_feedsteer.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer_feedsteer.setStyleSheet("QFrame{\n"
"    border-radius: 65px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer_feedsteer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer_feedsteer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer_feedsteer.setObjectName("circularContainer_feedsteer")
        self.layoutWidget = QtWidgets.QWidget(self.circularContainer_feedsteer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 111, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.infoLayout_feedsteer = QtWidgets.QGridLayout(self.layoutWidget)
        self.infoLayout_feedsteer.setContentsMargins(0, 0, 0, 0)
        self.infoLayout_feedsteer.setObjectName("infoLayout_feedsteer")
        self.label_feedsteer_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_feedsteer_2.setFont(font)
        self.label_feedsteer_2.setStyleSheet("color: #FFFFFF; background-color: none;")
        self.label_feedsteer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedsteer_2.setObjectName("label_feedsteer_2")
        self.infoLayout_feedsteer.addWidget(self.label_feedsteer_2, 0, 0, 1, 1)
        self.label_progress_feedsteer = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.label_progress_feedsteer.setFont(font)
        self.label_progress_feedsteer.setStyleSheet("color: rgb(115, 185, 255); padding: 0px; background-color: none;")
        self.label_progress_feedsteer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progress_feedsteer.setIndent(-1)
        self.label_progress_feedsteer.setObjectName("label_progress_feedsteer")
        self.infoLayout_feedsteer.addWidget(self.label_progress_feedsteer, 1, 0, 1, 1)
        self.label_feedsteer = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_feedsteer.setFont(font)
        self.label_feedsteer.setStyleSheet("color: rgb(148, 148, 216); background-color: none;")
        self.label_feedsteer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedsteer.setObjectName("label_feedsteer")
        self.infoLayout_feedsteer.addWidget(self.label_feedsteer, 2, 0, 1, 1)
        self.frame_buttonAuto = QtWidgets.QFrame(self.frame)
        self.frame_buttonAuto.setGeometry(QtCore.QRect(910, 10, 231, 381))
        self.frame_buttonAuto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttonAuto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttonAuto.setObjectName("frame_buttonAuto")
        self.button_dock = QtWidgets.QPushButton(self.frame_buttonAuto)
        self.button_dock.setGeometry(QtCore.QRect(20, 310, 191, 51))
        self.button_dock.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_dock.setObjectName("button_dock")
        self.button_check_steer = QtWidgets.QPushButton(self.frame_buttonAuto)
        self.button_check_steer.setGeometry(QtCore.QRect(20, 70, 191, 51))
        self.button_check_steer.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_check_steer.setObjectName("button_check_steer")
        self.button_check_throttle = QtWidgets.QPushButton(self.frame_buttonAuto)
        self.button_check_throttle.setGeometry(QtCore.QRect(20, 130, 191, 51))
        self.button_check_throttle.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_check_throttle.setObjectName("button_check_throttle")
        self.button_ps = QtWidgets.QPushButton(self.frame_buttonAuto)
        self.button_ps.setGeometry(QtCore.QRect(20, 250, 191, 51))
        self.button_ps.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_ps.setObjectName("button_ps")
        self.button_path = QtWidgets.QPushButton(self.frame_buttonAuto)
        self.button_path.setGeometry(QtCore.QRect(20, 190, 191, 51))
        self.button_path.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_path.setObjectName("button_path")
        self.label_buttonAuto1 = QtWidgets.QLabel(self.frame_buttonAuto)
        self.label_buttonAuto1.setGeometry(QtCore.QRect(49, 12, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_buttonAuto1.setFont(font)
        self.label_buttonAuto1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buttonAuto1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_buttonAuto1.setObjectName("label_buttonAuto1")
        self.label_buttonAuto2 = QtWidgets.QLabel(self.frame_buttonAuto)
        self.label_buttonAuto2.setGeometry(QtCore.QRect(50, 42, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_buttonAuto2.setFont(font)
        self.label_buttonAuto2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buttonAuto2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_buttonAuto2.setObjectName("label_buttonAuto2")
        self.frame_buttonLift = QtWidgets.QFrame(self.frame)
        self.frame_buttonLift.setGeometry(QtCore.QRect(910, 400, 231, 231))
        self.frame_buttonLift.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttonLift.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttonLift.setObjectName("frame_buttonLift")
        self.button_check_liftingUP = QtWidgets.QPushButton(self.frame_buttonLift)
        self.button_check_liftingUP.setGeometry(QtCore.QRect(20, 40, 191, 51))
        self.button_check_liftingUP.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_check_liftingUP.setObjectName("button_check_liftingUP")
        self.button_check_liftingMid = QtWidgets.QPushButton(self.frame_buttonLift)
        self.button_check_liftingMid.setGeometry(QtCore.QRect(20, 100, 191, 51))
        self.button_check_liftingMid.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_check_liftingMid.setObjectName("button_check_liftingMid")
        self.button_check_liftingDown = QtWidgets.QPushButton(self.frame_buttonLift)
        self.button_check_liftingDown.setGeometry(QtCore.QRect(20, 160, 191, 51))
        self.button_check_liftingDown.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_check_liftingDown.setObjectName("button_check_liftingDown")
        self.label_buttonLift = QtWidgets.QLabel(self.frame_buttonLift)
        self.label_buttonLift.setGeometry(QtCore.QRect(40, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_buttonLift.setFont(font)
        self.label_buttonLift.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buttonLift.setAlignment(QtCore.Qt.AlignCenter)
        self.label_buttonLift.setObjectName("label_buttonLift")
        self.frame_buttonAuto.raise_()
        self.sensorLidar.raise_()
        self.switch_move.raise_()
        self.switch_otonom.raise_()
        self.mathplotlib.raise_()
        self.sensorUltra.raise_()
        self.imageCTT.raise_()
        self.circular_feedBrake.raise_()
        self.circular_feedspeed.raise_()
        self.circular_feedsteer.raise_()
        self.sensorCamera.raise_()
        self.frame_buttonLift.raise_()
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_1_dashboard)
        self.page_2_log = QtWidgets.QWidget()
        self.page_2_log.setObjectName("page_2_log")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2_log)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layout_OD_AI = QtWidgets.QHBoxLayout()
        self.layout_OD_AI.setObjectName("layout_OD_AI")
        self.frame_OD = QtWidgets.QFrame(self.page_2_log)
        self.frame_OD.setStyleSheet("background-color: rgb(77, 77, 127);")
        self.frame_OD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_OD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_OD.setObjectName("frame_OD")
        self.frame_label_OD = QtWidgets.QFrame(self.frame_OD)
        self.frame_label_OD.setGeometry(QtCore.QRect(8, 10, 271, 61))
        self.frame_label_OD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_OD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_OD.setObjectName("frame_label_OD")
        self.label_OD = QtWidgets.QLabel(self.frame_label_OD)
        self.label_OD.setGeometry(QtCore.QRect(10, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_OD.setFont(font)
        self.label_OD.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_OD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OD.setObjectName("label_OD")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_OD)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(140, 100, 131, 521))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ob_kamera = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_kamera.setFont(font)
        self.ob_kamera.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_kamera.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_kamera.setIndent(-1)
        self.ob_kamera.setObjectName("ob_kamera")
        self.verticalLayout_12.addWidget(self.ob_kamera)
        self.ob_lidar = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_lidar.setFont(font)
        self.ob_lidar.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_lidar.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_lidar.setIndent(-1)
        self.ob_lidar.setObjectName("ob_lidar")
        self.verticalLayout_12.addWidget(self.ob_lidar)
        self.ob_ultra1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra1.setFont(font)
        self.ob_ultra1.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra1.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra1.setIndent(-1)
        self.ob_ultra1.setObjectName("ob_ultra1")
        self.verticalLayout_12.addWidget(self.ob_ultra1)
        self.ob_ultra2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra2.setFont(font)
        self.ob_ultra2.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra2.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra2.setIndent(-1)
        self.ob_ultra2.setObjectName("ob_ultra2")
        self.verticalLayout_12.addWidget(self.ob_ultra2)
        self.ob_ultra3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra3.setFont(font)
        self.ob_ultra3.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra3.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra3.setIndent(-1)
        self.ob_ultra3.setObjectName("ob_ultra3")
        self.verticalLayout_12.addWidget(self.ob_ultra3)
        self.ob_ultra4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra4.setFont(font)
        self.ob_ultra4.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra4.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra4.setIndent(-1)
        self.ob_ultra4.setObjectName("ob_ultra4")
        self.verticalLayout_12.addWidget(self.ob_ultra4)
        self.ob_ultra5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra5.setFont(font)
        self.ob_ultra5.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra5.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra5.setIndent(-1)
        self.ob_ultra5.setObjectName("ob_ultra5")
        self.verticalLayout_12.addWidget(self.ob_ultra5)
        self.ob_ultra6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra6.setFont(font)
        self.ob_ultra6.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra6.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra6.setIndent(-1)
        self.ob_ultra6.setObjectName("ob_ultra6")
        self.verticalLayout_12.addWidget(self.ob_ultra6)
        self.ob_ultra7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra7.setFont(font)
        self.ob_ultra7.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra7.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra7.setIndent(-1)
        self.ob_ultra7.setObjectName("ob_ultra7")
        self.verticalLayout_12.addWidget(self.ob_ultra7)
        self.ob_ultra8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ob_ultra8.setFont(font)
        self.ob_ultra8.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ob_ultra8.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_ultra8.setIndent(-1)
        self.ob_ultra8.setObjectName("ob_ultra8")
        self.verticalLayout_12.addWidget(self.ob_ultra8)
        self.ob_label_kamera = QtWidgets.QLabel(self.frame_OD)
        self.ob_label_kamera.setGeometry(QtCore.QRect(10, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ob_label_kamera.setFont(font)
        self.ob_label_kamera.setStyleSheet("color: rgb(255, 255, 255);")
        self.ob_label_kamera.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_label_kamera.setObjectName("ob_label_kamera")
        self.ob_label_lidar = QtWidgets.QLabel(self.frame_OD)
        self.ob_label_lidar.setGeometry(QtCore.QRect(10, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ob_label_lidar.setFont(font)
        self.ob_label_lidar.setStyleSheet("color: rgb(255, 255, 255);")
        self.ob_label_lidar.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_label_lidar.setObjectName("ob_label_lidar")
        self.ob_label_ultra = QtWidgets.QLabel(self.frame_OD)
        self.ob_label_ultra.setGeometry(QtCore.QRect(10, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ob_label_ultra.setFont(font)
        self.ob_label_ultra.setStyleSheet("color: rgb(255, 255, 255);")
        self.ob_label_ultra.setAlignment(QtCore.Qt.AlignCenter)
        self.ob_label_ultra.setObjectName("ob_label_ultra")
        self.layout_OD_AI.addWidget(self.frame_OD)
        self.frame_AI = QtWidgets.QFrame(self.page_2_log)
        self.frame_AI.setStyleSheet("background-color: rgb(77, 77, 127);")
        self.frame_AI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_AI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_AI.setObjectName("frame_AI")
        self.frame_label_AI = QtWidgets.QFrame(self.frame_AI)
        self.frame_label_AI.setGeometry(QtCore.QRect(9, 10, 271, 61))
        self.frame_label_AI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_AI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_AI.setObjectName("frame_label_AI")
        self.label_AI = QtWidgets.QLabel(self.frame_label_AI)
        self.label_AI.setGeometry(QtCore.QRect(10, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_AI.setFont(font)
        self.label_AI.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_AI.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AI.setObjectName("label_AI")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame_AI)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(150, 100, 121, 425))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ai_ecvlar = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_ecvlar.setFont(font)
        self.ai_ecvlar.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_ecvlar.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_ecvlar.setIndent(-1)
        self.ai_ecvlar.setObjectName("ai_ecvlar")
        self.verticalLayout_13.addWidget(self.ai_ecvlar)
        self.ai_ecvlav = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_ecvlav.setFont(font)
        self.ai_ecvlav.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_ecvlav.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_ecvlav.setIndent(-1)
        self.ai_ecvlav.setObjectName("ai_ecvlav")
        self.verticalLayout_13.addWidget(self.ai_ecvlav)
        self.ai_pt3 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_pt3.setFont(font)
        self.ai_pt3.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_pt3.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_pt3.setIndent(-1)
        self.ai_pt3.setObjectName("ai_pt3")
        self.verticalLayout_13.addWidget(self.ai_pt3)
        self.ai_zc2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_zc2.setFont(font)
        self.ai_zc2.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_zc2.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_zc2.setIndent(-1)
        self.ai_zc2.setObjectName("ai_zc2")
        self.verticalLayout_13.addWidget(self.ai_zc2)
        self.ai_zc6 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_zc6.setFont(font)
        self.ai_zc6.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_zc6.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_zc6.setIndent(-1)
        self.ai_zc6.setObjectName("ai_zc6")
        self.verticalLayout_13.addWidget(self.ai_zc6)
        self.ai_zc8 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_zc8.setFont(font)
        self.ai_zc8.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_zc8.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_zc8.setIndent(-1)
        self.ai_zc8.setObjectName("ai_zc8")
        self.verticalLayout_13.addWidget(self.ai_zc8)
        self.ai_zc7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_zc7.setFont(font)
        self.ai_zc7.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_zc7.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_zc7.setIndent(-1)
        self.ai_zc7.setObjectName("ai_zc7")
        self.verticalLayout_13.addWidget(self.ai_zc7)
        self.ai_zc3_to_ecu = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.ai_zc3_to_ecu.setFont(font)
        self.ai_zc3_to_ecu.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.ai_zc3_to_ecu.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_zc3_to_ecu.setIndent(-1)
        self.ai_zc3_to_ecu.setObjectName("ai_zc3_to_ecu")
        self.verticalLayout_13.addWidget(self.ai_zc3_to_ecu)
        self.ai_label_zc3_to_ecu = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_zc3_to_ecu.setGeometry(QtCore.QRect(20, 483, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_zc3_to_ecu.setFont(font)
        self.ai_label_zc3_to_ecu.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_zc3_to_ecu.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_zc3_to_ecu.setObjectName("ai_label_zc3_to_ecu")
        self.ai_label_zc2 = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_zc2.setGeometry(QtCore.QRect(20, 273, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_zc2.setFont(font)
        self.ai_label_zc2.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_zc2.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_zc2.setObjectName("ai_label_zc2")
        self.ai_label_pt3 = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_pt3.setGeometry(QtCore.QRect(20, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_pt3.setFont(font)
        self.ai_label_pt3.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_pt3.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_pt3.setObjectName("ai_label_pt3")
        self.ai_label_zc7 = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_zc7.setGeometry(QtCore.QRect(20, 430, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_zc7.setFont(font)
        self.ai_label_zc7.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_zc7.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_zc7.setObjectName("ai_label_zc7")
        self.ai_label_zc8 = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_zc8.setGeometry(QtCore.QRect(20, 380, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_zc8.setFont(font)
        self.ai_label_zc8.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_zc8.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_zc8.setObjectName("ai_label_zc8")
        self.ai_label_zc6 = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_zc6.setGeometry(QtCore.QRect(20, 327, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_zc6.setFont(font)
        self.ai_label_zc6.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_zc6.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_zc6.setObjectName("ai_label_zc6")
        self.ai_label_ecvlav = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_ecvlav.setGeometry(QtCore.QRect(20, 166, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_ecvlav.setFont(font)
        self.ai_label_ecvlav.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_ecvlav.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_ecvlav.setObjectName("ai_label_ecvlav")
        self.ai_label_ecvlar = QtWidgets.QLabel(self.frame_AI)
        self.ai_label_ecvlar.setGeometry(QtCore.QRect(20, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ai_label_ecvlar.setFont(font)
        self.ai_label_ecvlar.setStyleSheet("color: rgb(255, 255, 255);")
        self.ai_label_ecvlar.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_label_ecvlar.setObjectName("ai_label_ecvlar")
        self.layout_OD_AI.addWidget(self.frame_AI)
        self.horizontalLayout_3.addLayout(self.layout_OD_AI)
        self.layout_DI = QtWidgets.QHBoxLayout()
        self.layout_DI.setObjectName("layout_DI")
        self.frame_DI = QtWidgets.QFrame(self.page_2_log)
        self.frame_DI.setStyleSheet("background-color: rgb(77, 77, 127);")
        self.frame_DI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DI.setObjectName("frame_DI")
        self.frame_label_DI = QtWidgets.QFrame(self.frame_DI)
        self.frame_label_DI.setGeometry(QtCore.QRect(10, 10, 561, 61))
        self.frame_label_DI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_DI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_DI.setObjectName("frame_label_DI")
        self.label_DI = QtWidgets.QLabel(self.frame_label_DI)
        self.label_DI.setGeometry(QtCore.QRect(10, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_DI.setFont(font)
        self.label_DI.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_DI.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DI.setObjectName("label_DI")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_DI)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(440, 100, 131, 521))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_DI_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_DI_2.setContentsMargins(0, 0, 0, 0)
        self.layout_DI_2.setObjectName("layout_DI_2")
        self.di_ys3_1_to_pvg = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ys3_1_to_pvg.setFont(font)
        self.di_ys3_1_to_pvg.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ys3_1_to_pvg.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ys3_1_to_pvg.setIndent(-1)
        self.di_ys3_1_to_pvg.setObjectName("di_ys3_1_to_pvg")
        self.layout_DI_2.addWidget(self.di_ys3_1_to_pvg)
        self.di_ys3_2_to_pvg = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ys3_2_to_pvg.setFont(font)
        self.di_ys3_2_to_pvg.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ys3_2_to_pvg.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ys3_2_to_pvg.setIndent(-1)
        self.di_ys3_2_to_pvg.setObjectName("di_ys3_2_to_pvg")
        self.layout_DI_2.addWidget(self.di_ys3_2_to_pvg)
        self.di_esv1415_to_pvg_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_esv1415_to_pvg_2.setFont(font)
        self.di_esv1415_to_pvg_2.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_esv1415_to_pvg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_esv1415_to_pvg_2.setIndent(-1)
        self.di_esv1415_to_pvg_2.setObjectName("di_esv1415_to_pvg_2")
        self.layout_DI_2.addWidget(self.di_esv1415_to_pvg_2)
        self.di_ecv2_j19_to_pvg_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ecv2_j19_to_pvg_2.setFont(font)
        self.di_ecv2_j19_to_pvg_2.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ecv2_j19_to_pvg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ecv2_j19_to_pvg_2.setIndent(-1)
        self.di_ecv2_j19_to_pvg_2.setObjectName("di_ecv2_j19_to_pvg_2")
        self.layout_DI_2.addWidget(self.di_ecv2_j19_to_pvg_2)
        self.di_b01_nc = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_b01_nc.setFont(font)
        self.di_b01_nc.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_b01_nc.setAlignment(QtCore.Qt.AlignCenter)
        self.di_b01_nc.setIndent(-1)
        self.di_b01_nc.setObjectName("di_b01_nc")
        self.layout_DI_2.addWidget(self.di_b01_nc)
        self.di_c01_no = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_c01_no.setFont(font)
        self.di_c01_no.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_c01_no.setAlignment(QtCore.Qt.AlignCenter)
        self.di_c01_no.setIndent(-1)
        self.di_c01_no.setObjectName("di_c01_no")
        self.layout_DI_2.addWidget(self.di_c01_no)
        self.di_ls4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ls4.setFont(font)
        self.di_ls4.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ls4.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ls4.setIndent(-1)
        self.di_ls4.setObjectName("di_ls4")
        self.layout_DI_2.addWidget(self.di_ls4)
        self.di_av_to_actuator = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_av_to_actuator.setFont(font)
        self.di_av_to_actuator.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_av_to_actuator.setAlignment(QtCore.Qt.AlignCenter)
        self.di_av_to_actuator.setIndent(-1)
        self.di_av_to_actuator.setObjectName("di_av_to_actuator")
        self.layout_DI_2.addWidget(self.di_av_to_actuator)
        self.di_ar_to_actuator = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ar_to_actuator.setFont(font)
        self.di_ar_to_actuator.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ar_to_actuator.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ar_to_actuator.setIndent(-1)
        self.di_ar_to_actuator.setObjectName("di_ar_to_actuator")
        self.layout_DI_2.addWidget(self.di_ar_to_actuator)
        self.di_st1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_st1.setFont(font)
        self.di_st1.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_st1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_st1.setIndent(-1)
        self.di_st1.setObjectName("di_st1")
        self.layout_DI_2.addWidget(self.di_st1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_DI)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(160, 100, 131, 521))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.layout_DI_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_DI_1.setContentsMargins(0, 0, 0, 0)
        self.layout_DI_1.setObjectName("layout_DI_1")
        self.di_ps4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ps4.setFont(font)
        self.di_ps4.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ps4.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ps4.setIndent(-1)
        self.di_ps4.setObjectName("di_ps4")
        self.layout_DI_1.addWidget(self.di_ps4)
        self.di_ls2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ls2.setFont(font)
        self.di_ls2.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ls2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ls2.setIndent(-1)
        self.di_ls2.setObjectName("di_ls2")
        self.layout_DI_1.addWidget(self.di_ls2)
        self.di_ps1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ps1.setFont(font)
        self.di_ps1.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ps1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ps1.setIndent(-1)
        self.di_ps1.setObjectName("di_ps1")
        self.layout_DI_1.addWidget(self.di_ps1)
        self.di_pds1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_pds1.setFont(font)
        self.di_pds1.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_pds1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_pds1.setIndent(-1)
        self.di_pds1.setObjectName("di_pds1")
        self.layout_DI_1.addWidget(self.di_pds1)
        self.di_pds2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_pds2.setFont(font)
        self.di_pds2.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_pds2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_pds2.setIndent(-1)
        self.di_pds2.setObjectName("di_pds2")
        self.layout_DI_1.addWidget(self.di_pds2)
        self.di_ps2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ps2.setFont(font)
        self.di_ps2.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ps2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ps2.setIndent(-1)
        self.di_ps2.setObjectName("di_ps2")
        self.layout_DI_1.addWidget(self.di_ps2)
        self.di_ts1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ts1.setFont(font)
        self.di_ts1.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ts1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ts1.setIndent(-1)
        self.di_ts1.setObjectName("di_ts1")
        self.layout_DI_1.addWidget(self.di_ts1)
        self.di_ls1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_ls1.setFont(font)
        self.di_ls1.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_ls1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_ls1.setIndent(-1)
        self.di_ls1.setObjectName("di_ls1")
        self.layout_DI_1.addWidget(self.di_ls1)
        self.di_as = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_as.setFont(font)
        self.di_as.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_as.setAlignment(QtCore.Qt.AlignCenter)
        self.di_as.setIndent(-1)
        self.di_as.setObjectName("di_as")
        self.layout_DI_1.addWidget(self.di_as)
        self.di_eb = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.di_eb.setFont(font)
        self.di_eb.setStyleSheet("color: rgb(255, 44, 174); padding: 0px; background-color: none;")
        self.di_eb.setAlignment(QtCore.Qt.AlignCenter)
        self.di_eb.setIndent(-1)
        self.di_eb.setObjectName("di_eb")
        self.layout_DI_1.addWidget(self.di_eb)
        self.di_label_ps4 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ps4.setGeometry(QtCore.QRect(20, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ps4.setFont(font)
        self.di_label_ps4.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ps4.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ps4.setObjectName("di_label_ps4")
        self.di_label_ls2 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ls2.setGeometry(QtCore.QRect(20, 161, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ls2.setFont(font)
        self.di_label_ls2.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ls2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ls2.setObjectName("di_label_ls2")
        self.di_label_ps1 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ps1.setGeometry(QtCore.QRect(20, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ps1.setFont(font)
        self.di_label_ps1.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ps1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ps1.setObjectName("di_label_ps1")
        self.di_label_pds1 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_pds1.setGeometry(QtCore.QRect(20, 266, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_pds1.setFont(font)
        self.di_label_pds1.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_pds1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_pds1.setObjectName("di_label_pds1")
        self.di_label_pds2 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_pds2.setGeometry(QtCore.QRect(20, 317, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_pds2.setFont(font)
        self.di_label_pds2.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_pds2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_pds2.setObjectName("di_label_pds2")
        self.di_label_ps2 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ps2.setGeometry(QtCore.QRect(20, 369, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ps2.setFont(font)
        self.di_label_ps2.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ps2.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ps2.setObjectName("di_label_ps2")
        self.di_label_ts1 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ts1.setGeometry(QtCore.QRect(20, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ts1.setFont(font)
        self.di_label_ts1.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ts1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ts1.setObjectName("di_label_ts1")
        self.di_label_ls1 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ls1.setGeometry(QtCore.QRect(20, 470, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ls1.setFont(font)
        self.di_label_ls1.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ls1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ls1.setObjectName("di_label_ls1")
        self.di_label_as = QtWidgets.QLabel(self.frame_DI)
        self.di_label_as.setGeometry(QtCore.QRect(20, 525, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_as.setFont(font)
        self.di_label_as.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_as.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_as.setObjectName("di_label_as")
        self.di_label_eb = QtWidgets.QLabel(self.frame_DI)
        self.di_label_eb.setGeometry(QtCore.QRect(20, 573, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_eb.setFont(font)
        self.di_label_eb.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_eb.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_eb.setObjectName("di_label_eb")
        self.di_label_ys3_1_to_pvg = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ys3_1_to_pvg.setGeometry(QtCore.QRect(310, 109, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ys3_1_to_pvg.setFont(font)
        self.di_label_ys3_1_to_pvg.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ys3_1_to_pvg.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ys3_1_to_pvg.setObjectName("di_label_ys3_1_to_pvg")
        self.di_label_ys3_2_to_pvg = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ys3_2_to_pvg.setGeometry(QtCore.QRect(310, 161, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ys3_2_to_pvg.setFont(font)
        self.di_label_ys3_2_to_pvg.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ys3_2_to_pvg.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ys3_2_to_pvg.setObjectName("di_label_ys3_2_to_pvg")
        self.di_label_esv1415_to_pvg = QtWidgets.QLabel(self.frame_DI)
        self.di_label_esv1415_to_pvg.setGeometry(QtCore.QRect(304, 212, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.di_label_esv1415_to_pvg.setFont(font)
        self.di_label_esv1415_to_pvg.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_esv1415_to_pvg.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_esv1415_to_pvg.setObjectName("di_label_esv1415_to_pvg")
        self.di_label_esv2_j19_to_pvg = QtWidgets.QLabel(self.frame_DI)
        self.di_label_esv2_j19_to_pvg.setGeometry(QtCore.QRect(305, 268, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.di_label_esv2_j19_to_pvg.setFont(font)
        self.di_label_esv2_j19_to_pvg.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_esv2_j19_to_pvg.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_esv2_j19_to_pvg.setObjectName("di_label_esv2_j19_to_pvg")
        self.di_label_b01_nc = QtWidgets.QLabel(self.frame_DI)
        self.di_label_b01_nc.setGeometry(QtCore.QRect(310, 319, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_b01_nc.setFont(font)
        self.di_label_b01_nc.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_b01_nc.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_b01_nc.setObjectName("di_label_b01_nc")
        self.di_label_c01_no = QtWidgets.QLabel(self.frame_DI)
        self.di_label_c01_no.setGeometry(QtCore.QRect(310, 375, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_c01_no.setFont(font)
        self.di_label_c01_no.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_c01_no.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_c01_no.setObjectName("di_label_c01_no")
        self.di_label_ls4 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ls4.setGeometry(QtCore.QRect(306, 425, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_ls4.setFont(font)
        self.di_label_ls4.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ls4.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ls4.setObjectName("di_label_ls4")
        self.di_label_av_to_actuator = QtWidgets.QLabel(self.frame_DI)
        self.di_label_av_to_actuator.setGeometry(QtCore.QRect(300, 480, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.di_label_av_to_actuator.setFont(font)
        self.di_label_av_to_actuator.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_av_to_actuator.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_av_to_actuator.setObjectName("di_label_av_to_actuator")
        self.di_label_ar_to_actuator = QtWidgets.QLabel(self.frame_DI)
        self.di_label_ar_to_actuator.setGeometry(QtCore.QRect(300, 530, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.di_label_ar_to_actuator.setFont(font)
        self.di_label_ar_to_actuator.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_ar_to_actuator.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_ar_to_actuator.setObjectName("di_label_ar_to_actuator")
        self.di_label_st1 = QtWidgets.QLabel(self.frame_DI)
        self.di_label_st1.setGeometry(QtCore.QRect(300, 580, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.di_label_st1.setFont(font)
        self.di_label_st1.setStyleSheet("color: rgb(255, 255, 255);")
        self.di_label_st1.setAlignment(QtCore.Qt.AlignCenter)
        self.di_label_st1.setObjectName("di_label_st1")
        self.layout_DI.addWidget(self.frame_DI)
        self.horizontalLayout_3.addLayout(self.layout_DI)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page_2_log)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_menu.setText(_translate("MainWindow", "MENU"))
        self.label_title.setText(_translate("MainWindow", "AUTONOMOUS GUIDE VEHICLE (AGV) - CTT MERAH PUTIH"))
        self.btn_page_1.setText(_translate("MainWindow", "Dash"))
        self.btn_page_2.setText(_translate("MainWindow", "Log"))
        self.switch_netral_2.setText(_translate("MainWindow", " BACKWARD"))
        self.label_switch_otonom.setText(_translate("MainWindow", "AUTONOMOUS"))
        self.label_feedBrake_2.setText(_translate("MainWindow", "<html><head/><body><p>BREAK</p></body></html>"))
        self.label_progress_feedBrake.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">25</span></p></body></html>"))
        self.label_feedBrake.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">PERSEN</span></p></body></html>"))
        self.label_feedspeed_2.setText(_translate("MainWindow", "<html><head/><body><p>SPEED</p></body></html>"))
        self.label_progress_feedspeed.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">25</span></p></body></html>"))
        self.label_feedspeed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">KM/H</span></p></body></html>"))
        self.label_feedsteer_2.setText(_translate("MainWindow", "<html><head/><body><p>STEERING</p></body></html>"))
        self.label_progress_feedsteer.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">60</span></p></body></html>"))
        self.label_feedsteer.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">DEGREE</span></p></body></html>"))
        self.button_dock.setText(_translate("MainWindow", "DOCKING"))
        self.button_check_steer.setText(_translate("MainWindow", "CHECK STEER"))
        self.button_check_throttle.setText(_translate("MainWindow", "CHECK THROTTLE"))
        self.button_ps.setText(_translate("MainWindow", "POINT STABILIZATION"))
        self.button_path.setText(_translate("MainWindow", "PATH FOLLOWING"))
        self.label_buttonAuto1.setText(_translate("MainWindow", "AUTONOMOUS"))
        self.label_buttonAuto2.setText(_translate("MainWindow", "BUTTON"))
        self.button_check_liftingUP.setText(_translate("MainWindow", "LIFTING UP"))
        self.button_check_liftingMid.setText(_translate("MainWindow", "LIFTING MID"))
        self.button_check_liftingDown.setText(_translate("MainWindow", "LIFTING DOWN"))
        self.label_buttonLift.setText(_translate("MainWindow", "LIFTING BUTTON"))
        self.label_OD.setText(_translate("MainWindow", "OBJECT DETECTION"))
        self.ob_kamera.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_lidar.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_ultra8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ob_label_kamera.setText(_translate("MainWindow", "KAMERA"))
        self.ob_label_lidar.setText(_translate("MainWindow", "LiDAR"))
        self.ob_label_ultra.setText(_translate("MainWindow", "ULTRASONIK"))
        self.label_AI.setText(_translate("MainWindow", "ANALOG INPUT"))
        self.ai_ecvlar.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_ecvlav.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_pt3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_zc2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_zc6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_zc8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_zc7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_zc3_to_ecu.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.ai_label_zc3_to_ecu.setText(_translate("MainWindow", "ZC3 to ECU"))
        self.ai_label_zc2.setText(_translate("MainWindow", "ZC2"))
        self.ai_label_pt3.setText(_translate("MainWindow", "PT3"))
        self.ai_label_zc7.setText(_translate("MainWindow", "ZC7"))
        self.ai_label_zc8.setText(_translate("MainWindow", "ZC8"))
        self.ai_label_zc6.setText(_translate("MainWindow", "ZC6"))
        self.ai_label_ecvlav.setText(_translate("MainWindow", "ECVLAV"))
        self.ai_label_ecvlar.setText(_translate("MainWindow", "ECVLAR"))
        self.label_DI.setText(_translate("MainWindow", "DIGITAL INPUT"))
        self.di_ys3_1_to_pvg.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ys3_2_to_pvg.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_esv1415_to_pvg_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ecv2_j19_to_pvg_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_b01_nc.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_c01_no.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ls4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_av_to_actuator.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ar_to_actuator.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_st1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ps4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ls2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ps1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_pds1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_pds2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ps2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ts1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_ls1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_as.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_eb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">0</span></p></body></html>"))
        self.di_label_ps4.setText(_translate("MainWindow", "PS4"))
        self.di_label_ls2.setText(_translate("MainWindow", "LS2"))
        self.di_label_ps1.setText(_translate("MainWindow", "PS1"))
        self.di_label_pds1.setText(_translate("MainWindow", "PDS1"))
        self.di_label_pds2.setText(_translate("MainWindow", "PDS2"))
        self.di_label_ps2.setText(_translate("MainWindow", "PS2"))
        self.di_label_ts1.setText(_translate("MainWindow", "TS1"))
        self.di_label_ls1.setText(_translate("MainWindow", "LS1"))
        self.di_label_as.setText(_translate("MainWindow", "AUTO SWITCH"))
        self.di_label_eb.setText(_translate("MainWindow", "EMERGENCY"))
        self.di_label_ys3_1_to_pvg.setText(_translate("MainWindow", "YS3(1) to PVG"))
        self.di_label_ys3_2_to_pvg.setText(_translate("MainWindow", "YS3(2) to PVG"))
        self.di_label_esv1415_to_pvg.setText(_translate("MainWindow", "ESV1415 to PVG"))
        self.di_label_esv2_j19_to_pvg.setText(_translate("MainWindow", "ECV2 J19 to PVG"))
        self.di_label_b01_nc.setText(_translate("MainWindow", "B01 NC"))
        self.di_label_c01_no.setText(_translate("MainWindow", "C01 NO"))
        self.di_label_ls4.setText(_translate("MainWindow", "LS4"))
        self.di_label_av_to_actuator.setText(_translate("MainWindow", "AV to ACTUATOR"))
        self.di_label_ar_to_actuator.setText(_translate("MainWindow", "AR to ACTUATOR"))
        self.di_label_st1.setText(_translate("MainWindow", "ST1"))

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

